title: RightBTC FAQ
subtitle: "RightBTC official API website."
description: "RightBTC Dedicated to providing quality cryptocurrency trading services Professional digital asset wallet services,RightBTC official API website."
author: RightBTC
language: en
timezone: UTC

url: https://www.rightbtc.com
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:hexojs/hexojs.github.io.git

highlight:
  enable: true
  line_number: false

disqus_shortname: hexojs
google_analytics: UA-48498357-3
fb_admins: 100000247608790

# algolia:
#   en:
#     api_key: c3d5d4c995b5e0c2ffb5623900279a66
#     index_name: hexo
#   zh-tw:
#     api_key: c83d2ec3440f40aec6d0e695ecec7ef3
#     index_name: hexo_zh-tw
#   zh-cn:
#     api_key: cdea7d4e47d84f6145b77e7f68689f35
#     index_name: hexo_zh-cn

twitter: Rightbtc_
facebook: rightbtc
github: rightbtc


Regeneration: --watch


# hexo-admin authentification
admin:
  username: zoro
  password_hash: $2a$10$5B8qUToAjRNcncTI0DruhewgmyeL3ealA.0W1qEjeCLhDOGjAV.pW
  secret: hey hexo